# Generated by Django 4.0.5 on 2022-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_tfa_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300, null=True)),
                ('token', models.CharField(max_length=300, null=True, unique=True)),
            ],
        ),
    ]
